---
version: '3.8'
services:
  kitoborui:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: kitoborui
    # image: kitoborcom/kitoborui:main
    restart: unless-stopped
    ports:
      - "8080:80"
